baseURL = 'https://sungatae.com/'
languageCode = 'en-us'
title = 'sung·a·tae'
theme = 'hugo-theme-minos'
enableGitInfo = true

[services]
    [services.disqus]
        shortname = 'sungatae-com'

[menus]
  [[menus.main]]
    name = 'posts'
    pageRef = '/posts'
    weight = 10
  [[menus.main]]
    name = 'videos'
    pageRef = '/videos'
    weight = 20
  [[menus.main]]
    name = 'ig'
    url = 'https://ig.sungatae.com'
    weight = 30